networks:
  shine_network:
    driver: bridge

services:
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: shine-sql-server-container
    restart: always
    environment:
      SA_PASSWORD: "IEXzYzjos-F0c"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - shine_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Shine-Service-Users
    restart: always
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=shine-sql-server-container,1433;Database=UserDb;User Id=sa;Password=IEXzYzjos-F0c;
    ports:
      - "5000:5000"
    networks:
      - shine_network